version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
  - package-ecosystem: "npm"
    directory: "/claimant"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
    ignore:
      # The USWDS version should be managed manually
      # and coordinated with the ReactUSWDS version.
      - dependency-name: "uswds"
