version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
  - package-ecosystem: "npm"
    directory: "/initclaim"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
