version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
    ignore:
      - dependency-name: "Django"
        versions:
          - ">=4.0.0"
  - package-ecosystem: "npm"
    directory: "/claimant"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "America/New_York"
    ignore:
      # The USWDS version should be managed manually
      # and coordinated with the ReactUSWDS version.
      - dependency-name: "uswds"
      # msw needs node 16, our .node-version is below that;
      # this can be removed once we upgrade node
      - dependency-name: "msw"
        update-types: ["version-update:semver-minor"]
