# consumes the Dockerfile for use in GitHub Actions CI pipeline
version: "3"
networks:
  app-tier:
    driver: bridge
services:
  web:
    depends_on:
      - "rds"
      - "localstack"
      - "elasticache"
    networks:
      - app-tier
    container_name: web
    image: dolui:${ENV_NAME}
    build:
      context: .
      target: djangobase-ci
      args:
        ENV_NAME: ${ENV_NAME}
    ports:
      - "8004:8000"
    command: ["wait-for-it", "rds:3306", "--", "./start-server.sh"]
