# this docker compose mimics running full AWS stack locally
# it is *not* for running the UI Django app(s). It's for the external services that
# the Django app(s) rely on.
version: "3.3"
networks:
  app-tier:
    driver: bridge
services:
  rds:
    networks:
      - app-tier
    container_name: mysqlserver
    image: mysql:8.0
    restart: always
    environment:
      # So you don"t have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "secret"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "secretpassword"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # Where our data will be persisted
    volumes:
      - ui-db:/var/lib/mysql
      - ./scripts/mysqld-init:/docker-entrypoint-initdb.d

  # https://github.com/localstack/localstack/ provides local mock AWS services
  localstack:
    networks:
      - app-tier
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/aws-init:/docker-entrypoint-initaws.d"

  elasticache:
    networks:
      - app-tier
    container_name: elasticache-redis
    image: docker.io/bitnami/redis:6.2
    ports:
      - "6379:6379"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      # - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - REDIS_TLS_ENABLED=yes
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_PORT=6379
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis-server.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis-server.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/redisCA.crt
    volumes:
      - "redis-data:/bitnami/redis/data"
      - "./certs:/opt/bitnami/redis/certs"

# volumes persist when docker not running
volumes:
  ui-db:
  certs:
  redis-data:
    driver: local
