# consumes the Dockerfile for use in GitHub Actions CI pipeline
version: "3"
networks:
  app-tier:
    driver: bridge
services:
  web:
    networks:
      - app-tier
    container_name: web
    image: dolui:ci
    build:
      context: .
      args:
        ENV_NAME: ci
    ports:
      - "8000:8000"
    # set env at run time, but also populate the build args values
    env_file:
      - ./core/.env-ci
