env:
  browser: true
  node: true
  commonjs: true
  es2021: true
  jest: true
parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "17"
rules:
  "react/react-in-jsx-scope": "off"
  "react/jsx-filename-extension":
    [1, { "extensions": [".js", ".jsx", ".ts", ".tsx"] }]
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "react/prop-types": "off"
